### ISSUE TITLE
Shouldn't commit these. 

### ISSUE THREAD

**Issue by aequasi** [meedan/pender#178]
https://github.com/meedan/pender/blob/746a28ca4d8332872a12da989c62fc2967607e82/lib/tasks/aws.rake#L8

**Comment by caiosba** [comment]
It's a fake one, that's why it ends in `EXAMPLE` :)

**Comment by infojunkie** [comment]
@danielafeitosa do we actually need this rake task? Looks like a test.

**Comment by danielafeitosa** [comment]
@infojunkie we don't need, I'll remove it
